name: Auto Clean and Merge IPTV

on:
  schedule:
    - cron: '0 21 * * *' # 天天國際標準時間 21:00，等同於台灣時間每日早上 05:00 自動執行更新
  workflow_dispatch: # 允許您在網頁上隨時手動點擊「立即更新」

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python merge_iptv.py

    - name: Commit and Push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add taiwan_live.m3u
        git commit -m "每日早上05:00定時更新台灣多線路清單" || exit 0
        git push
